using System.Globalization;
using System.Text;
using Asn1Kit.Codegen;
using Asn1Kit.Ir;

namespace Asn1Kit.Codegen.CSharp;

public sealed class CSharpBackend : ILanguageBackend
{
    private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "class", "namespace", "event", "string", "object", "int", "bool", "null", "value", "base", "this"
    };

    public string LanguageId => "csharp";

    public IReadOnlyList<GeneratedFile> Generate(IrDocument document)
    {
        return document.Modules.Select(module => GenerateModule(document, module)).ToList();
    }

    private GeneratedFile GenerateModule(IrDocument document, IrModule module)
    {
        var ns = IrOptions.CSharpNamespace(module.Options) ?? SanitizeIdentifier(module.Name);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Numerics;");
        builder.AppendLine("using Asn1Kit.Runtime;");
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        var queue = new Queue<(string Name, TypeExpr Type)>();
        foreach (var type in module.Types)
        {
            if (!IrOptions.ShouldGenerate(type.Options))
            {
                continue;
            }

            var typeName = IrOptions.CSharpTypeName(type.Options) ?? SanitizeIdentifier(type.Name);
            queue.Enqueue((typeName, type.Type));
        }

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var nested = new List<(string Name, TypeExpr Type)>();
        while (queue.Count > 0)
        {
            var (name, type) = queue.Dequeue();
            if (!emitted.Add(name))
            {
                continue;
            }

            CollectNested(document, module, name, type, queue);
            nested.Add((name, type));
        }

        foreach (var (name, type) in nested)
        {
            EmitType(builder, document, module, name, type);
            builder.AppendLine();
        }

        return new GeneratedFile(SanitizeIdentifier(module.Name) + ".g.cs", builder.ToString());
    }

    private void CollectNested(
        IrDocument document,
        IrModule module,
        string owner,
        TypeExpr type,
        Queue<(string Name, TypeExpr Type)> queue)
    {
        switch (type)
        {
            case SequenceType sequence:
                foreach (var component in sequence.Components)
                {
                    OfferNested(document, module, owner + "_" + SanitizeIdentifier(component.Name), component.Type, queue);
                }

                break;
            case ChoiceType choice:
                foreach (var component in choice.Components)
                {
                    OfferNested(document, module, owner + "_" + SanitizeIdentifier(component.Name), component.Type, queue);
                }

                break;
            case SequenceOfType sequenceOf:
                OfferNested(document, module, owner + "Item", sequenceOf.Element, queue);
                break;
        }
    }

    private void OfferNested(
        IrDocument document,
        IrModule module,
        string hint,
        TypeExpr type,
        Queue<(string Name, TypeExpr Type)> queue)
    {
        if (NeedsNamedType(type))
        {
            queue.Enqueue((hint, WithoutTag(type)));
            CollectNested(document, module, hint, WithoutTag(type), queue);
        }
        else if (type is RefType)
        {
            return;
        }
        else if (type is SequenceOfType or SequenceType or ChoiceType)
        {
            CollectNested(document, module, hint, type, queue);
        }
    }

    private static TypeExpr WithoutTag(TypeExpr type)
    {
        // Nested class uses the inner encoding; the field's tag is applied by the parent.
        type.Tag = type.Tag;
        return type;
    }

    private static bool NeedsNamedType(TypeExpr type) =>
        type is SequenceType or ChoiceType or SequenceOfType;

    private void EmitType(StringBuilder sb, IrDocument document, IrModule module, string typeName, TypeExpr type)
    {
        EnsureBackendSupport(type);
        switch (type)
        {
            case SequenceType sequence:
                EmitSequence(sb, document, module, typeName, sequence);
                break;
            case ChoiceType choice:
                EmitChoice(sb, document, module, typeName, choice);
                break;
            case SequenceOfType sequenceOf:
                EmitSequenceOf(sb, document, module, typeName, sequenceOf);
                break;
            default:
                EmitAlias(sb, document, module, typeName, type);
                break;
        }
    }

    private static void EnsureBackendSupport(TypeExpr type)
    {
        switch (type)
        {
            case BitStringType:
            case StringType:
            case TimeType:
            case AnyType:
            case SetType:
            case SetOfType:
                throw new NotSupportedException(
                    $"C# backend does not support kind '{type.Kind}' yet.");
            case SequenceType sequence:
                foreach (var component in sequence.Components)
                {
                    EnsureBackendSupport(component.Type);
                }

                break;
            case ChoiceType choice:
                foreach (var component in choice.Components)
                {
                    EnsureBackendSupport(component.Type);
                }

                break;
            case SequenceOfType sequenceOf:
                EnsureBackendSupport(sequenceOf.Element);
                break;
        }
    }

    private void EmitSequence(StringBuilder sb, IrDocument document, IrModule module, string typeName, SequenceType type)
    {
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        foreach (var field in type.Components)
        {
            var prop = PropertyName(field);
            var csType = CsType(document, module, typeName, field.Name, field.Type, field.Optional);
            sb.AppendLine($"    public {csType} {prop} {{ get; set; }}{Initializer(field.Type, field.Optional)}");
        }

        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSequence(tag, inner =>");
        sb.AppendLine("        {");
        foreach (var field in type.Components)
        {
            EmitEncodeField(sb, document, module, typeName, field, "            ", "inner");
        }

        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        foreach (var field in type.Components)
        {
            EmitDecodeField(sb, document, module, typeName, field, "            ", "inner", "value");
        }

        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, constructed: true, fallback: "Asn1Tag.Sequence");
        sb.AppendLine("}");
    }

    private void EmitChoice(StringBuilder sb, IrDocument document, IrModule module, string typeName, ChoiceType type)
    {
        sb.AppendLine($"public enum {typeName}Kind");
        sb.AppendLine("{");
        foreach (var field in type.Components)
        {
            sb.AppendLine($"    {PropertyName(field)},");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {typeName}Kind Kind {{ get; private set; }}");
        foreach (var field in type.Components)
        {
            var prop = PropertyName(field);
            var csType = CsType(document, module, typeName, field.Name, field.Type, optional: true);
            sb.AppendLine($"    public {csType} {prop} {{ get; private set; }}");
        }

        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (Kind)");
        sb.AppendLine("        {");
        foreach (var field in type.Components)
        {
            var prop = PropertyName(field);
            sb.AppendLine($"            case {typeName}Kind.{prop}:");
            EmitEncodeValue(sb, document, module, typeName, field.Name, field.Type, "                ", "writer", UnwrapOptional(field.Type, prop));
            sb.AppendLine("                break;");
        }

        sb.AppendLine("            default: throw new Asn1Exception(\"CHOICE has no alternative.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!reader.TryPeekTag(out var peeked)) throw new Asn1Exception(\"Empty CHOICE.\");");
        sb.AppendLine($"        var value = new {typeName}();");
        var first = true;
        foreach (var field in type.Components)
        {
            var prop = PropertyName(field);
            var cond = first ? "if" : "else if";
            first = false;
            sb.AppendLine($"        {cond} (peeked.MatchesIgnoreConstructed({TagExpr(document, module, field.Type)}))");
            sb.AppendLine("        {");
            sb.AppendLine($"            value.Kind = {typeName}Kind.{prop};");
            EmitDecodeAssign(sb, document, module, typeName, field.Name, field.Type, "            ", "reader", $"value.{prop}");
            sb.AppendLine("        }");
        }

        sb.AppendLine("        else throw new Asn1Exception(\"Unknown CHOICE alternative.\");");
        sb.AppendLine("        return value;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private void EmitSequenceOf(StringBuilder sb, IrDocument document, IrModule module, string typeName, SequenceOfType type)
    {
        var itemType = CsType(document, module, typeName, "Item", type.Element, optional: false);
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public List<{itemType}> Items {{ get; set; }} = new List<{itemType}>();");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var item in Items)");
        sb.AppendLine("            {");
        EmitEncodeValue(sb, document, module, typeName, "Item", type.Element, "                ", "inner", "item");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        sb.AppendLine("            while (!inner.Eof)");
        sb.AppendLine("            {");
        sb.Append("                value.Items.Add(");
        EmitDecodeExpr(sb, document, module, typeName, "Item", type.Element, "inner");
        sb.AppendLine(");");
        sb.AppendLine("            }");
        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, constructed: true, fallback: "Asn1Tag.Sequence");
        sb.AppendLine("}");
    }

    private void EmitAlias(StringBuilder sb, IrDocument document, IrModule module, string typeName, TypeExpr type)
    {
        var csType = CsType(document, module, typeName, "Value", type, optional: false);
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {csType} Value {{ get; set; }}{Initializer(type, false)}");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        var untagged = CloneUntagged(type);
        EmitEncodeValue(sb, document, module, typeName, "Value", untagged, "        ", "writer", "Value", forceTag: "tag");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var value = new {typeName}();");
        EmitDecodeAssign(sb, document, module, typeName, "Value", untagged, "        ", "reader", "value.Value", forceTag: "tag");
        sb.AppendLine("        return value;");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, IsConstructed(document, module, type), UniversalFallback(type));
        sb.AppendLine("}");
    }

    private static void EmitDefaultTag(StringBuilder sb, TypeExpr type, bool constructed, string fallback)
    {
        var tag = type.Tag is null ? fallback : TagFromIr(type.Tag, constructed || type.Tag.Mode == TagModes.Explicit);
        sb.AppendLine();
        sb.AppendLine($"    public static Asn1Tag DefaultTag {{ get; }} = {tag};");
    }

    private void EmitEncodeField(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        IrComponent field,
        string indent,
        string writer)
    {
        var prop = PropertyName(field);
        if (field.Optional)
        {
            sb.AppendLine($"{indent}if ({prop} != null)");
            sb.AppendLine($"{indent}{{");
            EmitEncodeValue(sb, document, module, owner, field.Name, field.Type, indent + "    ", writer, UnwrapOptional(field.Type, prop));
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            EmitEncodeValue(sb, document, module, owner, field.Name, field.Type, indent, writer, prop);
        }
    }

    private string UnwrapOptional(TypeExpr type, string expr)
    {
        return IsValueOptionalWrapper(type) ? expr + ".Value" : expr;
    }

    private bool IsValueOptionalWrapper(TypeExpr type) =>
        ResolvePrimitive(type) is TypeKinds.Boolean or TypeKinds.Integer or TypeKinds.Enumerated;

    private void EmitEncodeValue(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        string hint,
        TypeExpr type,
        string indent,
        string writer,
        string expr,
        string? forceTag = null)
    {
        if (type.Tag?.Mode == TagModes.Explicit && forceTag is null)
        {
            sb.AppendLine($"{indent}{writer}.WriteExplicit({TagFromIr(type.Tag, constructed: true)}, nested =>");
            sb.AppendLine($"{indent}{{");
            var inner = CloneUntagged(type);
            EmitEncodeValue(sb, document, module, owner, hint, inner, indent + "    ", "nested", expr);
            sb.AppendLine($"{indent}}});");
            return;
        }

        var tag = forceTag ?? TagExpr(document, module, type);
        var primitive = ResolvePrimitive(type);
        if (primitive is not null && type is not RefType)
        {
            if (primitive == TypeKinds.Null)
            {
                sb.AppendLine($"{indent}{writer}.WriteNull({tag});");
                return;
            }

            sb.AppendLine($"{indent}{writer}.{WriteMethod(primitive)}({tag}, {expr});");
            return;
        }

        if (type is RefType reference)
        {
            var resolved = Find(document, module, reference);
            if (resolved?.Type is ChoiceType)
            {
                sb.AppendLine($"{indent}{expr}.Encode({writer});");
                return;
            }
        }

        if (type is ChoiceType)
        {
            sb.AppendLine($"{indent}{expr}.Encode({writer});");
            return;
        }

        sb.AppendLine($"{indent}{expr}.Encode({writer}, {tag});");
    }

    private void EmitDecodeField(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        IrComponent field,
        string indent,
        string reader,
        string target)
    {
        var prop = PropertyName(field);
        if (field.Optional)
        {
            sb.AppendLine($"{indent}if ({reader}.TryPeekTag(out var tag_{field.Name}) && tag_{field.Name}.MatchesIgnoreConstructed({TagExpr(document, module, field.Type)}))");
            sb.AppendLine($"{indent}{{");
            EmitDecodeAssign(sb, document, module, owner, field.Name, field.Type, indent + "    ", reader, $"{target}.{prop}");
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            EmitDecodeAssign(sb, document, module, owner, field.Name, field.Type, indent, reader, $"{target}.{prop}");
        }
    }

    private void EmitDecodeAssign(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        string hint,
        TypeExpr type,
        string indent,
        string reader,
        string target,
        string? forceTag = null)
    {
        sb.Append(indent);
        sb.Append(target);
        sb.Append(" = ");
        EmitDecodeExpr(sb, document, module, owner, hint, type, reader, forceTag);
        sb.AppendLine(";");
    }

    private void EmitDecodeExpr(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        string hint,
        TypeExpr type,
        string reader,
        string? forceTag = null)
    {
        if (type.Tag?.Mode == TagModes.Explicit && forceTag is null)
        {
            sb.Append($"{reader}.ReadSequence({TagFromIr(type.Tag, constructed: true)}, nested => ");
            EmitDecodeExpr(sb, document, module, owner, hint, CloneUntagged(type), "nested");
            sb.Append(')');
            return;
        }

        var tag = forceTag ?? TagExpr(document, module, type);
        var primitive = ResolvePrimitive(type);
        if (primitive is not null && type is not RefType)
        {
            if (primitive == TypeKinds.Null)
            {
                sb.Append($"{reader}.ReadNull({tag})");
                return;
            }

            sb.Append($"{reader}.{ReadMethod(primitive)}({tag})");
            return;
        }

        var typeName = NamedTypeName(document, module, owner, hint, type);
        if (type is ChoiceType || (type is RefType r && Find(document, module, r)?.Type is ChoiceType))
        {
            sb.Append($"{typeName}.Decode({reader})");
            return;
        }

        sb.Append($"{typeName}.Decode({reader}, {tag})");
    }

    private string CsType(IrDocument document, IrModule module, string owner, string hint, TypeExpr type, bool optional)
    {
        var primitive = ResolvePrimitive(type);
        if (primitive is not null && type is not RefType)
        {
            var mapped = primitive switch
            {
                TypeKinds.Boolean => optional ? "bool?" : "bool",
                TypeKinds.Integer or TypeKinds.Enumerated => optional ? "BigInteger?" : "BigInteger",
                TypeKinds.OctetString => optional ? "byte[]?" : "byte[]",
                TypeKinds.Null => optional ? "bool?" : "bool",
                TypeKinds.Oid => optional ? "string?" : "string",
                _ => "object"
            };
            return mapped;
        }

        var name = NamedTypeName(document, module, owner, hint, type);
        return optional ? name + "?" : name;
    }

    private string NamedTypeName(IrDocument document, IrModule module, string owner, string hint, TypeExpr type)
    {
        if (type is RefType reference)
        {
            var def = Find(document, module, reference);
            if (def is not null)
            {
                return IrOptions.CSharpTypeName(def.Options) ?? SanitizeIdentifier(def.Name);
            }

            return SanitizeIdentifier(reference.Name);
        }

        if (NeedsNamedType(type))
        {
            return owner + "_" + SanitizeIdentifier(hint);
        }

        return SanitizeIdentifier(hint);
    }

    private static string Initializer(TypeExpr type, bool optional)
    {
        if (optional)
        {
            return "";
        }

        return type switch
        {
            OctetStringType => " = Array.Empty<byte>();",
            OidType => " = \"\";",
            SequenceOfType => " = new();",
            _ => ""
        };
    }

    private string TagExpr(IrDocument document, IrModule module, TypeExpr type)
    {
        if (type.Tag is not null)
        {
            var constructed = type.Tag.Mode == TagModes.Explicit || IsConstructed(document, module, type);
            return TagFromIr(type.Tag, constructed);
        }

        return UniversalTag(document, module, type);
    }

    private static string TagFromIr(IrTag tag, bool constructed)
    {
        var cls = tag.Class.ToLowerInvariant() switch
        {
            TagClasses.Universal => "Asn1TagClass.Universal",
            TagClasses.Application => "Asn1TagClass.Application",
            TagClasses.Private => "Asn1TagClass.Private",
            _ => "Asn1TagClass.ContextSpecific"
        };

        return $"new Asn1Tag({cls}, {tag.Number.ToString(CultureInfo.InvariantCulture)}, {(constructed ? "true" : "false")})";
    }

    private string UniversalTag(IrDocument document, IrModule module, TypeExpr type)
    {
        var primitive = ResolvePrimitive(type);
        return primitive switch
        {
            TypeKinds.Boolean => "Asn1Tag.Boolean",
            TypeKinds.Integer or TypeKinds.Enumerated => "Asn1Tag.Integer",
            TypeKinds.OctetString => "Asn1Tag.OctetString",
            TypeKinds.Null => "Asn1Tag.Null",
            TypeKinds.Oid => "Asn1Tag.ObjectIdentifier",
            _ => IsConstructed(document, module, type) ? "Asn1Tag.Sequence" : "Asn1Tag.Sequence"
        };
    }

    private static string UniversalFallback(TypeExpr type) => type switch
    {
        BooleanType => "Asn1Tag.Boolean",
        IntegerType or EnumeratedType => "Asn1Tag.Integer",
        OctetStringType => "Asn1Tag.OctetString",
        NullType => "Asn1Tag.Null",
        OidType => "Asn1Tag.ObjectIdentifier",
        _ => "Asn1Tag.Sequence"
    };

    private string? ResolvePrimitive(TypeExpr type) => type switch
    {
        BooleanType => TypeKinds.Boolean,
        IntegerType => TypeKinds.Integer,
        EnumeratedType => TypeKinds.Enumerated,
        OctetStringType => TypeKinds.OctetString,
        NullType => TypeKinds.Null,
        OidType => TypeKinds.Oid,
        _ => null
    };

    private bool IsConstructed(IrDocument document, IrModule module, TypeExpr type) => type switch
    {
        SequenceType or SequenceOfType or ChoiceType => true,
        RefType reference => Find(document, module, reference)?.Type is { } inner && IsConstructed(document, module, inner),
        _ => false
    };

    private static IrTypeDef? Find(IrDocument document, IrModule module, RefType reference)
    {
        var modules = string.IsNullOrEmpty(reference.Module)
            ? new[] { module }.Concat(document.Modules)
            : document.Modules.Where(m => m.Name == reference.Module);
        foreach (var candidate in modules)
        {
            var match = candidate.Types.FirstOrDefault(t => t.Name == reference.Name);
            if (match is not null)
            {
                return match;
            }
        }

        return null;
    }

    private static TypeExpr CloneUntagged(TypeExpr type)
    {
        var clone = type switch
        {
            BooleanType => (TypeExpr)new BooleanType(),
            NullType => new NullType(),
            OctetStringType => new OctetStringType(),
            OidType => new OidType(),
            IntegerType integer => new IntegerType { NamedValues = integer.NamedValues },
            EnumeratedType enumerated => new EnumeratedType { Values = enumerated.Values },
            SequenceType sequence => new SequenceType { Components = sequence.Components },
            ChoiceType choice => new ChoiceType { Components = choice.Components },
            SequenceOfType sequenceOf => new SequenceOfType { Element = sequenceOf.Element },
            RefType reference => new RefType { Name = reference.Name, Module = reference.Module },
            _ => type
        };
        clone.Options = type.Options;
        return clone;
    }

    private static string WriteMethod(string primitive) => primitive switch
    {
        TypeKinds.Boolean => "WriteBoolean",
        TypeKinds.Integer or TypeKinds.Enumerated => "WriteInteger",
        TypeKinds.OctetString => "WriteOctetString",
        TypeKinds.Null => "WriteNull",
        TypeKinds.Oid => "WriteObjectIdentifier",
        _ => throw new InvalidOperationException(primitive)
    };

    private static string ReadMethod(string primitive) => primitive switch
    {
        TypeKinds.Boolean => "ReadBoolean",
        TypeKinds.Integer or TypeKinds.Enumerated => "ReadInteger",
        TypeKinds.OctetString => "ReadOctetString",
        TypeKinds.Null => "ReadNull",
        TypeKinds.Oid => "ReadObjectIdentifier",
        _ => throw new InvalidOperationException(primitive)
    };

    private static string PropertyName(IrComponent field)
    {
        var name = IrOptions.CSharpPropertyName(field.Options) ?? SanitizeIdentifier(field.Name);
        return Keywords.Contains(name) ? "@" + name : name;
    }

    internal static string SanitizeIdentifier(string name)
    {
        var parts = name.Split(new[] { '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
        var result = string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : "")));
        return string.IsNullOrEmpty(result) ? "Type" : result;
    }
}
