using System.Globalization;
using System.Text;
using Asn1Kit.Codegen;
using Asn1Kit.Ir;

namespace Asn1Kit.Codegen.CSharp;

public sealed class CSharpBackend : ILanguageBackend
{
    private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "class", "namespace", "event", "string", "object", "int", "bool", "null", "value", "base", "this"
    };

    public string LanguageId => "csharp";

    public IReadOnlyList<GeneratedFile> Generate(IrModule module)
    {
        var ns = OptionString(module.Options, OptionKeys.CSharpNamespace) ?? SanitizeIdentifier(module.Module);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Numerics;");
        builder.AppendLine("using Asn1Kit.Runtime;");
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        foreach (var type in module.Types)
        {
            if (IsDisabled(type.Options))
            {
                continue;
            }

            EmitType(builder, module, type);
            builder.AppendLine();
        }

        var fileName = SanitizeIdentifier(module.Module) + ".g.cs";
        return new[] { new GeneratedFile(fileName, builder.ToString()) };
    }

    private void EmitType(StringBuilder sb, IrModule module, IrTypeDef type)
    {
        var typeName = OptionString(type.Options, OptionKeys.CSharpTypeName) ?? SanitizeIdentifier(type.Name);
        switch (type.Kind)
        {
            case TypeKinds.Sequence:
                EmitSequence(sb, module, type, typeName);
                break;
            case TypeKinds.Choice:
                EmitChoice(sb, module, type, typeName);
                break;
            case TypeKinds.SequenceOf:
                EmitSequenceOf(sb, module, type, typeName);
                break;
            case TypeKinds.Alias:
                EmitAlias(sb, module, type, typeName);
                break;
            default:
                throw new InvalidOperationException($"Unsupported kind '{type.Kind}'.");
        }
    }

    private void EmitSequence(StringBuilder sb, IrModule module, IrTypeDef type, string typeName)
    {
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        foreach (var field in type.Fields!)
        {
            var prop = PropertyName(field);
            var csType = CsType(module, field.Type, field.Optional);
            sb.AppendLine($"    public {csType} {prop} {{ get; set; }}{PropertyInitializer(module, field.Type, field.Optional)}");
        }

        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSequence(tag, inner =>");
        sb.AppendLine("        {");
        foreach (var field in type.Fields)
        {
            EmitEncodeField(sb, module, field, "            ", "inner");
        }

        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        foreach (var field in type.Fields)
        {
            EmitDecodeField(sb, module, field, "            ", "inner", "value");
        }

        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, module, type, constructed: true);
        sb.AppendLine("}");
    }

    private void EmitChoice(StringBuilder sb, IrModule module, IrTypeDef type, string typeName)
    {
        sb.AppendLine($"public enum {typeName}Kind");
        sb.AppendLine("{");
        foreach (var field in type.Fields!)
        {
            sb.AppendLine($"    {PropertyName(field)},");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {typeName}Kind Kind {{ get; private set; }}");
        foreach (var field in type.Fields)
        {
            var prop = PropertyName(field);
            var csType = CsType(module, field.Type, optional: true);
            sb.AppendLine($"    public {csType} {prop} {{ get; private set; }}");
        }

        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (Kind)");
        sb.AppendLine("        {");
        foreach (var field in type.Fields)
        {
            var prop = PropertyName(field);
            sb.AppendLine($"            case {typeName}Kind.{prop}:");
            EmitEncodeFieldValue(sb, module, field, "                ", "writer", prop);
            sb.AppendLine("                break;");
        }

        sb.AppendLine("            default: throw new Asn1Exception(\"CHOICE has no alternative.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!reader.TryPeekTag(out var peeked)) throw new Asn1Exception(\"Empty CHOICE.\");");
        sb.AppendLine($"        var value = new {typeName}();");
        var first = true;
        foreach (var field in type.Fields)
        {
            var prop = PropertyName(field);
            var cond = first ? "if" : "else if";
            first = false;
            sb.AppendLine($"        {cond} (peeked.MatchesIgnoreConstructed({TagExpr(module, field)}))");
            sb.AppendLine("        {");
            sb.AppendLine($"            value.Kind = {typeName}Kind.{prop};");
            EmitDecodeAssign(sb, module, field, "            ", "reader", $"value.{prop}");
            sb.AppendLine("        }");
        }

        sb.AppendLine("        else throw new Asn1Exception(\"Unknown CHOICE alternative.\");");
        sb.AppendLine("        return value;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private void EmitSequenceOf(StringBuilder sb, IrModule module, IrTypeDef type, string typeName)
    {
        var element = type.ElementType!;
        var itemType = CsType(module, element, optional: false);
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public List<{itemType}> Items {{ get; set; }} = new List<{itemType}>();");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var item in Items)");
        sb.AppendLine("            {");
        var fakeField = new IrField { Name = "item", Type = element };
        EmitEncodeFieldValue(sb, module, fakeField, "                ", "inner", "item");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        sb.AppendLine("            while (!inner.Eof)");
        sb.AppendLine("            {");
        sb.Append($"                ");
        EmitDecodeAdd(sb, module, element, "inner", "value.Items");
        sb.AppendLine("            }");
        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, module, type, constructed: true);
        sb.AppendLine("}");
    }

    private void EmitAlias(StringBuilder sb, IrModule module, IrTypeDef type, string typeName)
    {
        var inner = type.Type!;
        var csType = CsType(module, inner, optional: false);
        var constructed = IsConstructed(module, inner);
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {csType} Value {{ get; set; }}{PropertyInitializer(module, inner, false)}");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        var fake = new IrField { Name = "Value", Type = inner };
        EmitEncodeFieldValue(sb, module, fake, "        ", "writer", "Value", forceTag: "tag");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var value = new {typeName}();");
        EmitDecodeAssign(sb, module, fake, "        ", "reader", "value.Value", forceTag: "tag");
        sb.AppendLine("        return value;");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, module, type, constructed);
        sb.AppendLine("}");
    }

    private void EmitDefaultTag(StringBuilder sb, IrModule module, IrTypeDef type, bool constructed)
    {
        var tag = type.Tag is null
            ? UniversalExpr(module, type.Kind == TypeKinds.Alias ? type.Type! : type.Name, constructed || type.Kind is TypeKinds.Sequence or TypeKinds.SequenceOf)
            : TagFromIr(type.Tag, constructed || type.Tag.Mode == TagModes.Explicit);
        if (type.Kind is TypeKinds.Sequence or TypeKinds.SequenceOf)
        {
            tag = type.Tag is null ? "Asn1Tag.Sequence" : TagFromIr(type.Tag, constructed: true);
        }

        sb.AppendLine();
        sb.AppendLine($"    public static Asn1Tag DefaultTag {{ get; }} = {tag};");
    }

    private void EmitEncodeField(StringBuilder sb, IrModule module, IrField field, string indent, string writer)
    {
        var prop = PropertyName(field);
        if (field.Optional)
        {
            sb.AppendLine($"{indent}if ({prop} != null)");
            sb.AppendLine($"{indent}{{");
            EmitEncodeFieldValue(sb, module, field, indent + "    ", writer, prop + (NeedsValueUnwrap(module, field) ? ".Value" : ""));
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            EmitEncodeFieldValue(sb, module, field, indent, writer, prop);
        }
    }

    private bool NeedsValueUnwrap(IrModule module, IrField field)
    {
        if (!field.Optional)
        {
            return false;
        }

        var primitive = ResolvePrimitive(module, field.Type);
        return primitive is BuiltinTypes.Boolean or BuiltinTypes.Integer;
    }

    private void EmitEncodeFieldValue(
        StringBuilder sb,
        IrModule module,
        IrField field,
        string indent,
        string writer,
        string expr,
        string? forceTag = null)
    {
        var tag = forceTag ?? TagExpr(module, field);
        if (field.Tag?.Mode == TagModes.Explicit && forceTag is null)
        {
            sb.AppendLine($"{indent}{writer}.WriteExplicit({TagFromIr(field.Tag, constructed: true)}, nested =>");
            sb.AppendLine($"{indent}{{");
            var innerField = new IrField { Name = field.Name, Type = field.Type };
            EmitEncodeFieldValue(sb, module, innerField, indent + "    ", "nested", expr);
            sb.AppendLine($"{indent}}});");
            return;
        }

        var primitive = ResolvePrimitive(module, field.Type);
        if (primitive is not null && !IsUserType(module, field.Type))
        {
            sb.AppendLine($"{indent}{writer}.{WriteMethod(primitive)}({tag}, {expr});");
            return;
        }

        if (BuiltinTypes.IsBuiltin(field.Type))
        {
            sb.AppendLine($"{indent}{writer}.{WriteMethod(field.Type)}({tag}, {expr});");
            return;
        }

        var typeDef = Find(module, field.Type);
        if (typeDef?.Kind == TypeKinds.Choice)
        {
            sb.AppendLine($"{indent}{expr}.Encode({writer});");
            return;
        }

        sb.AppendLine($"{indent}{expr}.Encode({writer}, {tag});");
    }

    private void EmitDecodeField(StringBuilder sb, IrModule module, IrField field, string indent, string reader, string target)
    {
        var prop = PropertyName(field);
        if (field.Optional)
        {
            sb.AppendLine($"{indent}if ({reader}.TryPeekTag(out var tag_{field.Name}) && tag_{field.Name}.MatchesIgnoreConstructed({TagExpr(module, field)}))");
            sb.AppendLine($"{indent}{{");
            EmitDecodeAssign(sb, module, field, indent + "    ", reader, $"{target}.{prop}");
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            EmitDecodeAssign(sb, module, field, indent, reader, $"{target}.{prop}");
        }
    }

    private void EmitDecodeAssign(
        StringBuilder sb,
        IrModule module,
        IrField field,
        string indent,
        string reader,
        string target,
        string? forceTag = null)
    {
        var tag = forceTag ?? TagExpr(module, field);
        if (field.Tag?.Mode == TagModes.Explicit && forceTag is null)
        {
            sb.AppendLine($"{indent}{target} = {reader}.ReadSequence({TagFromIr(field.Tag, constructed: true)}, nested =>");
            sb.AppendLine($"{indent}{{");
            var innerField = new IrField { Name = field.Name, Type = field.Type };
            sb.Append($"{indent}    ");
            sb.Append(CsType(module, field.Type, false));
            sb.Append(" innerValue = default!;");
            sb.AppendLine();
            EmitDecodeAssign(sb, module, innerField, indent + "    ", "nested", "innerValue");
            sb.AppendLine($"{indent}    return innerValue;");
            sb.AppendLine($"{indent}}});");
            return;
        }

        if (BuiltinTypes.IsBuiltin(field.Type) || ResolvePrimitive(module, field.Type) is { } prim && !IsUserType(module, field.Type))
        {
            var builtin = BuiltinTypes.IsBuiltin(field.Type) ? field.Type : ResolvePrimitive(module, field.Type)!;
            if (builtin == BuiltinTypes.Null)
            {
                sb.AppendLine($"{indent}{reader}.ReadNull({tag});");
                sb.AppendLine($"{indent}{target} = true;");
                return;
            }

            sb.AppendLine($"{indent}{target} = {reader}.{ReadMethod(builtin)}({tag});");
            return;
        }

        var typeName = TypeNameOf(module, field.Type);
        var typeDef = Find(module, field.Type);
        if (typeDef?.Kind == TypeKinds.Choice)
        {
            sb.AppendLine($"{indent}{target} = {typeName}.Decode({reader});");
            return;
        }

        sb.AppendLine($"{indent}{target} = {typeName}.Decode({reader}, {tag});");
    }

    private void EmitDecodeAdd(StringBuilder sb, IrModule module, string elementType, string reader, string list)
    {
        var field = new IrField { Name = "item", Type = elementType };
        if (BuiltinTypes.IsBuiltin(elementType))
        {
            sb.AppendLine($"{list}.Add({reader}.{ReadMethod(elementType)}({UniversalExpr(module, elementType, false)}));");
            return;
        }

        var typeName = TypeNameOf(module, elementType);
        var typeDef = Find(module, elementType);
        if (typeDef?.Kind == TypeKinds.Choice)
        {
            sb.AppendLine($"{list}.Add({typeName}.Decode({reader}));");
        }
        else
        {
            sb.AppendLine($"{list}.Add({typeName}.Decode({reader}, {typeName}.DefaultTag));");
        }
    }

    private static string WriteMethod(string builtin) => builtin switch
    {
        BuiltinTypes.Boolean => "WriteBoolean",
        BuiltinTypes.Integer => "WriteInteger",
        BuiltinTypes.OctetString => "WriteOctetString",
        BuiltinTypes.Null => "WriteNull",
        BuiltinTypes.ObjectIdentifier => "WriteObjectIdentifier",
        _ => throw new InvalidOperationException(builtin)
    };

    private static string ReadMethod(string builtin) => builtin switch
    {
        BuiltinTypes.Boolean => "ReadBoolean",
        BuiltinTypes.Integer => "ReadInteger",
        BuiltinTypes.OctetString => "ReadOctetString",
        BuiltinTypes.Null => "ReadNull",
        BuiltinTypes.ObjectIdentifier => "ReadObjectIdentifier",
        _ => throw new InvalidOperationException(builtin)
    };

    private string TagExpr(IrModule module, IrField field)
    {
        if (field.Tag is not null)
        {
            var constructed = field.Tag.Mode == TagModes.Explicit || IsConstructed(module, field.Type);
            return TagFromIr(field.Tag, constructed);
        }

        return UniversalExpr(module, field.Type, IsConstructed(module, field.Type));
    }

    private static string TagFromIr(IrTag tag, bool constructed)
    {
        var cls = tag.Class.ToLowerInvariant() switch
        {
            TagClasses.Universal => "Asn1TagClass.Universal",
            TagClasses.Application => "Asn1TagClass.Application",
            TagClasses.Private => "Asn1TagClass.Private",
            _ => "Asn1TagClass.ContextSpecific"
        };

        var ctor = constructed ? "true" : "false";
        return $"new Asn1Tag({cls}, {tag.Number.ToString(CultureInfo.InvariantCulture)}, {ctor})";
    }

    private string UniversalExpr(IrModule module, string typeName, bool constructedHint)
    {
        var primitive = ResolvePrimitive(module, typeName);
        if (primitive == BuiltinTypes.Boolean) return "Asn1Tag.Boolean";
        if (primitive == BuiltinTypes.Integer) return "Asn1Tag.Integer";
        if (primitive == BuiltinTypes.OctetString) return "Asn1Tag.OctetString";
        if (primitive == BuiltinTypes.Null) return "Asn1Tag.Null";
        if (primitive == BuiltinTypes.ObjectIdentifier) return "Asn1Tag.ObjectIdentifier";
        return constructedHint ? "Asn1Tag.Sequence" : "Asn1Tag.Sequence";
    }

    private string CsType(IrModule module, string typeName, bool optional)
    {
        if (BuiltinTypes.IsBuiltin(typeName) || (!IsUserType(module, typeName) && ResolvePrimitive(module, typeName) is { } p))
        {
            var builtin = BuiltinTypes.IsBuiltin(typeName) ? typeName : ResolvePrimitive(module, typeName)!;
            var mapped = builtin switch
            {
                BuiltinTypes.Boolean => optional ? "bool?" : "bool",
                BuiltinTypes.Integer => optional ? "BigInteger?" : "BigInteger",
                BuiltinTypes.OctetString => optional ? "byte[]?" : "byte[]",
                BuiltinTypes.Null => optional ? "bool?" : "bool",
                BuiltinTypes.ObjectIdentifier => optional ? "string?" : "string",
                _ => "object"
            };
            return mapped;
        }

        var name = TypeNameOf(module, typeName);
        return optional ? name + "?" : name;
    }

    private static string PropertyInitializer(IrModule module, string typeName, bool optional)
    {
        if (optional)
        {
            return "";
        }

        if (typeName == BuiltinTypes.OctetString)
        {
            return " = Array.Empty<byte>();";
        }

        if (typeName == BuiltinTypes.ObjectIdentifier)
        {
            return " = \"\";";
        }

        return "";
    }

    private string TypeNameOf(IrModule module, string typeName)
    {
        var def = Find(module, typeName);
        if (def is null)
        {
            return SanitizeIdentifier(typeName);
        }

        return OptionString(def.Options, OptionKeys.CSharpTypeName) ?? SanitizeIdentifier(def.Name);
    }

    private static IrTypeDef? Find(IrModule module, string name) =>
        module.Types.FirstOrDefault(t => t.Name == name);

    private bool IsUserType(IrModule module, string name) => Find(module, name) is not null;

    private bool IsConstructed(IrModule module, string typeName)
    {
        var def = Find(module, typeName);
        if (def is null)
        {
            return false;
        }

        return def.Kind switch
        {
            TypeKinds.Sequence or TypeKinds.SequenceOf or TypeKinds.Choice => true,
            TypeKinds.Alias => IsConstructed(module, def.Type!),
            _ => false
        };
    }

    private string? ResolvePrimitive(IrModule module, string typeName)
    {
        if (BuiltinTypes.IsBuiltin(typeName))
        {
            return typeName;
        }

        var def = Find(module, typeName);
        if (def?.Kind == TypeKinds.Alias)
        {
            return ResolvePrimitive(module, def.Type!);
        }

        return null;
    }

    private static bool IsDisabled(Dictionary<string, object?> options)
    {
        if (!options.TryGetValue(OptionKeys.Generate, out var value) || value is null)
        {
            return false;
        }

        return value is false or "false";
    }

    private static string? OptionString(Dictionary<string, object?> options, string key)
    {
        return options.TryGetValue(key, out var value) ? value?.ToString() : null;
    }

    private static string PropertyName(IrField field)
    {
        var name = OptionString(field.Options, OptionKeys.CSharpPropertyName) ?? SanitizeIdentifier(field.Name);
        return Keywords.Contains(name) ? "@" + name : name;
    }

    internal static string SanitizeIdentifier(string name)
    {
        var parts = name.Split(new[] { '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
        var result = string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : "")));
        return string.IsNullOrEmpty(result) ? "Type" : result;
    }
}
