<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Asn1Kit.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Asn1Kit.Ir\Asn1Kit.Ir.csproj" />
  </ItemGroup>

</Project>
