using System.Globalization;
using System.Text;
using Asn1Kit.Codegen;
using Asn1Kit.Ir;

namespace Asn1Kit.Codegen.CSharp;

public sealed class CSharpBackend : ILanguageBackend
{
    private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "class", "namespace", "event", "string", "object", "int", "bool", "null", "value", "base", "this"
    };

    public string LanguageId => "csharp";

    public IReadOnlyList<GeneratedFile> Generate(IrDocument document)
    {
        return document.Modules.Select(module => GenerateModule(document, module)).ToList();
    }

    private GeneratedFile GenerateModule(IrDocument document, IrModule module)
    {
        var ns = ModuleNamespace(module);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Numerics;");
        builder.AppendLine("using Asn1Kit.Runtime;");
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        var queue = new Queue<(string Name, TypeExpr Type)>();
        foreach (var type in module.Types)
        {
            if (!IrOptions.ShouldGenerate(type.Options))
            {
                continue;
            }

            if (IsCollapsibleAlias(type.Type))
            {
                continue;
            }

            var typeName = IrOptions.CSharpTypeName(type.Options) ?? SanitizeIdentifier(type.Name);
            queue.Enqueue((typeName, type.Type));
        }

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var nested = new List<(string Name, TypeExpr Type)>();
        while (queue.Count > 0)
        {
            var (name, type) = queue.Dequeue();
            if (!emitted.Add(name))
            {
                continue;
            }

            CollectNested(document, module, name, type, queue);
            nested.Add((name, type));
        }

        foreach (var (name, type) in nested)
        {
            EmitType(builder, document, module, name, type);
            builder.AppendLine();
        }

        return new GeneratedFile(SanitizeIdentifier(module.Name) + ".g.cs", builder.ToString());
    }

    private void CollectNested(
        IrDocument document,
        IrModule module,
        string owner,
        TypeExpr type,
        Queue<(string Name, TypeExpr Type)> queue)
    {
        switch (type)
        {
            case SequenceType sequence:
                foreach (var component in sequence.Components)
                {
                    OfferNested(document, module, owner + "_" + SanitizeIdentifier(component.Name), component.Type, queue);
                }

                break;
            case SetType set:
                foreach (var component in set.Components)
                {
                    OfferNested(document, module, owner + "_" + SanitizeIdentifier(component.Name), component.Type, queue);
                }

                break;
            case ChoiceType choice:
                foreach (var component in choice.Components)
                {
                    OfferNested(document, module, owner + "_" + SanitizeIdentifier(component.Name), component.Type, queue);
                }

                break;
            case SequenceOfType sequenceOf:
                OfferNested(document, module, owner + "_Item", sequenceOf.Element, queue);
                break;
            case SetOfType setOf:
                OfferNested(document, module, owner + "_Item", setOf.Element, queue);
                break;
        }
    }

    private void OfferNested(
        IrDocument document,
        IrModule module,
        string hint,
        TypeExpr type,
        Queue<(string Name, TypeExpr Type)> queue)
    {
        if (NeedsNamedType(type))
        {
            queue.Enqueue((hint, WithoutTag(type)));
            CollectNested(document, module, hint, WithoutTag(type), queue);
        }
        else if (type is RefType)
        {
            return;
        }
        else if (type is SequenceOfType or SetOfType or SequenceType or SetType or ChoiceType)
        {
            CollectNested(document, module, hint, type, queue);
        }
    }

    private static TypeExpr WithoutTag(TypeExpr type)
    {
        // Nested class uses the inner encoding; the field's tag is applied by the parent.
        type.Tag = type.Tag;
        return type;
    }

    private static bool NeedsNamedType(TypeExpr type) =>
        type is SequenceType or SetType or ChoiceType or SequenceOfType or SetOfType;

    private static bool IsNamedBitString(TypeExpr type) =>
        type is BitStringType { NamedBits: { Count: > 0 } };

    /// <summary>Typedefs that must not get their own C# class (collapsed to the underlying type).</summary>
    private static bool IsCollapsibleAlias(TypeExpr type) =>
        !NeedsNamedType(type) && !IsNamedBitString(type);

    private void EmitType(StringBuilder sb, IrDocument document, IrModule module, string typeName, TypeExpr type)
    {
        EnsureBackendSupport(type);
        switch (type)
        {
            case SequenceType sequence:
                EmitSequence(sb, document, module, typeName, sequence);
                break;
            case SetType set:
                EmitSet(sb, document, module, typeName, set);
                break;
            case ChoiceType choice:
                EmitChoice(sb, document, module, typeName, choice);
                break;
            case SequenceOfType sequenceOf:
                EmitSequenceOf(sb, document, module, typeName, sequenceOf);
                break;
            case SetOfType setOf:
                EmitSetOf(sb, document, module, typeName, setOf);
                break;
            case BitStringType bitString when IsNamedBitString(bitString):
                EmitNamedBitString(sb, typeName, bitString);
                break;
            default:
                throw new InvalidOperationException(
                    $"C# backend refused to emit collapsible alias '{typeName}' (kind '{type.Kind}').");
        }
    }

    private static void EnsureBackendSupport(TypeExpr type)
    {
        switch (type)
        {
            case SequenceType sequence:
                foreach (var component in sequence.Components)
                {
                    EnsureBackendSupport(component.Type);
                }

                break;
            case SetType set:
                foreach (var component in set.Components)
                {
                    EnsureBackendSupport(component.Type);
                }

                break;
            case ChoiceType choice:
                foreach (var component in choice.Components)
                {
                    EnsureBackendSupport(component.Type);
                }

                break;
            case SequenceOfType sequenceOf:
                EnsureBackendSupport(sequenceOf.Element);
                break;
            case SetOfType setOf:
                EnsureBackendSupport(setOf.Element);
                break;
        }
    }

    private void EmitSequence(StringBuilder sb, IrDocument document, IrModule module, string typeName, SequenceType type)
    {
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        foreach (var field in type.Components)
        {
            EmitProperty(sb, document, module, typeName, field, field.Optional, privateSetter: false);
        }

        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSequence(tag, inner =>");
        sb.AppendLine("        {");
        foreach (var field in type.Components)
        {
            EmitEncodeField(sb, document, module, typeName, field, "            ", "inner");
        }

        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        foreach (var field in type.Components)
        {
            EmitDecodeField(sb, document, module, typeName, field, "            ", "inner", "value");
        }

        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, constructed: true, fallback: "Asn1Tag.Sequence");
        sb.AppendLine("}");
    }

    private void EmitSet(StringBuilder sb, IrDocument document, IrModule module, string typeName, SetType type)
    {
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        foreach (var field in type.Components)
        {
            EmitProperty(sb, document, module, typeName, field, field.Optional, privateSetter: false);
        }

        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSet(tag, inner =>");
        sb.AppendLine("        {");
        foreach (var field in SortedSetComponents(document, module, type.Components))
        {
            EmitEncodeField(sb, document, module, typeName, field, "            ", "inner");
        }

        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSet(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        foreach (var field in type.Components)
        {
            if (!field.Optional)
            {
                sb.AppendLine($"            var seen_{SanitizeIdentifier(field.Name)} = false;");
            }
        }

        sb.AppendLine("            while (!inner.Eof)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!inner.TryPeekTag(out var peeked))");
        sb.AppendLine("                {");
        sb.AppendLine("                    break;");
        sb.AppendLine("                }");
        var first = true;
        foreach (var field in type.Components)
        {
            var prop = PropertyName(field, typeName);
            var cond = first ? "if" : "else if";
            first = false;
            sb.AppendLine($"                {cond} (peeked.MatchesIgnoreConstructed({TagExpr(document, module, field.Type)}))");
            sb.AppendLine("                {");
            if (!field.Optional)
            {
                var seen = $"seen_{SanitizeIdentifier(field.Name)}";
                sb.AppendLine($"                    if ({seen}) throw new Asn1Exception(\"Duplicate SET component '{field.Name}'.\");");
                sb.AppendLine($"                    {seen} = true;");
            }
            else
            {
                sb.AppendLine($"                    if (value.{prop} != null) throw new Asn1Exception(\"Duplicate SET component '{field.Name}'.\");");
            }

            EmitDecodeAssign(sb, document, module, typeName, field.Name, field.Type, "                    ", "inner", $"value.{prop}");
            sb.AppendLine("                }");
        }

        sb.AppendLine("                else throw new Asn1Exception(\"Unknown SET component.\");");
        sb.AppendLine("            }");
        foreach (var field in type.Components)
        {
            if (!field.Optional)
            {
                sb.AppendLine(
                    $"            if (!seen_{SanitizeIdentifier(field.Name)}) throw new Asn1Exception(\"Missing SET component '{field.Name}'.\");");
            }
        }

        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, constructed: true, fallback: "Asn1Tag.Set");
        sb.AppendLine("}");
    }

    private void EmitChoice(StringBuilder sb, IrDocument document, IrModule module, string typeName, ChoiceType type)
    {
        sb.AppendLine($"public enum {typeName}Kind");
        sb.AppendLine("{");
        foreach (var field in type.Components)
        {
            sb.AppendLine($"    {PropertyName(field, typeName)},");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {typeName}Kind Kind {{ get; private set; }}");
        foreach (var field in type.Components)
        {
            EmitProperty(sb, document, module, typeName, field, optional: true, privateSetter: true);
        }

        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (Kind)");
        sb.AppendLine("        {");
        foreach (var field in type.Components)
        {
            var prop = PropertyName(field, typeName);
            sb.AppendLine($"            case {typeName}Kind.{prop}:");
            EmitEncodeValue(
                sb,
                document,
                module,
                typeName,
                field.Name,
                field.Type,
                "                ",
                "writer",
                UnwrapOptional(document, module, field.Type, prop));
            sb.AppendLine("                break;");
        }

        sb.AppendLine("            default: throw new Asn1Exception(\"CHOICE has no alternative.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!reader.TryPeekTag(out var peeked)) throw new Asn1Exception(\"Empty CHOICE.\");");
        sb.AppendLine($"        var value = new {typeName}();");
        var first = true;
        foreach (var field in type.Components)
        {
            var prop = PropertyName(field, typeName);
            var cond = first ? "if" : "else if";
            first = false;
            sb.AppendLine($"        {cond} (peeked.MatchesIgnoreConstructed({TagExpr(document, module, field.Type)}))");
            sb.AppendLine("        {");
            sb.AppendLine($"            value.Kind = {typeName}Kind.{prop};");
            EmitDecodeAssign(sb, document, module, typeName, field.Name, field.Type, "            ", "reader", $"value.{prop}");
            sb.AppendLine("        }");
        }

        sb.AppendLine("        else throw new Asn1Exception(\"Unknown CHOICE alternative.\");");
        sb.AppendLine("        return value;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private void EmitSequenceOf(StringBuilder sb, IrDocument document, IrModule module, string typeName, SequenceOfType type)
    {
        var itemType = CsType(document, module, typeName, "Item", type.Element, optional: false);
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public List<{itemType}> Items {{ get; set; }} = new List<{itemType}>();");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var item in Items)");
        sb.AppendLine("            {");
        EmitEncodeValue(sb, document, module, typeName, "Item", type.Element, "                ", "inner", "item");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSequence(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        sb.AppendLine("            while (!inner.Eof)");
        sb.AppendLine("            {");
        sb.Append("                value.Items.Add(");
        EmitDecodeExpr(sb, document, module, typeName, "Item", type.Element, "inner");
        sb.AppendLine(");");
        sb.AppendLine("            }");
        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, constructed: true, fallback: "Asn1Tag.Sequence");
        sb.AppendLine("}");
    }

    private void EmitSetOf(StringBuilder sb, IrDocument document, IrModule module, string typeName, SetOfType type)
    {
        var itemType = CsType(document, module, typeName, "Item", type.Element, optional: false);
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public List<{itemType}> Items {{ get; set; }} = new List<{itemType}>();");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteSetOf(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var item in Items)");
        sb.AppendLine("            {");
        EmitEncodeValue(sb, document, module, typeName, "Item", type.Element, "                ", "inner", "item");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return reader.ReadSet(tag, inner =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var value = new {typeName}();");
        sb.AppendLine("            while (!inner.Eof)");
        sb.AppendLine("            {");
        sb.Append("                value.Items.Add(");
        EmitDecodeExpr(sb, document, module, typeName, "Item", type.Element, "inner");
        sb.AppendLine(");");
        sb.AppendLine("            }");
        sb.AppendLine("            return value;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, constructed: true, fallback: "Asn1Tag.Set");
        sb.AppendLine("}");
    }

    private void EmitNamedBitString(StringBuilder sb, string typeName, BitStringType type)
    {
        var namedBits = type.NamedBits!;
        var maxIndex = namedBits.Max(b => b.Value);
        if (maxIndex > 62)
        {
            throw new NotSupportedException(
                $"Named BIT STRING '{typeName}' bit index {maxIndex} exceeds Flags enum limit (62).");
        }

        var useLong = maxIndex > 30;
        var enumName = typeName + "Flags";
        var shiftSuffix = useLong ? "L" : "";

        sb.AppendLine("[Flags]");
        sb.Append("public enum ").Append(enumName);
        if (useLong)
        {
            sb.Append(" : long");
        }

        sb.AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    None = 0,");
        for (var i = 0; i < namedBits.Count; i++)
        {
            var bit = namedBits[i];
            var member = SanitizeIdentifier(bit.Name);
            sb.AppendLine(
                $"    /// <summary>ASN.1 named bit {bit.Name}({bit.Value.ToString(CultureInfo.InvariantCulture)}).</summary>");
            sb.Append($"    {member} = 1{shiftSuffix} << {bit.Value.ToString(CultureInfo.InvariantCulture)}");
            sb.AppendLine(i + 1 < namedBits.Count ? "," : "");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine("    public Asn1BitString Value { get; set; }");
        sb.AppendLine();
        sb.AppendLine($"    public {enumName} Flags");
        sb.AppendLine("    {");
        sb.AppendLine("        get => ToFlags(Value);");
        sb.AppendLine("        set => Value = FromFlags(value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {enumName} ToFlags(Asn1BitString bits)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var flags = {enumName}.None;");
        foreach (var bit in namedBits)
        {
            var member = SanitizeIdentifier(bit.Name);
            var index = bit.Value.ToString(CultureInfo.InvariantCulture);
            sb.AppendLine(
                $"        if (bits.BitLength > {index} && bits[{index}]) flags |= {enumName}.{member};");
        }

        sb.AppendLine("        return flags;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static Asn1BitString FromFlags({enumName} flags)");
        sb.AppendLine("    {");
        var length = ((int)maxIndex + 1).ToString(CultureInfo.InvariantCulture);
        sb.AppendLine($"        var bits = new bool[{length}];");
        foreach (var bit in namedBits)
        {
            var member = SanitizeIdentifier(bit.Name);
            var index = bit.Value.ToString(CultureInfo.InvariantCulture);
            sb.AppendLine(
                $"        if ((flags & {enumName}.{member}) != 0) bits[{index}] = true;");
        }

        sb.AppendLine("        var length = bits.Length;");
        sb.AppendLine("        while (length > 0 && !bits[length - 1])");
        sb.AppendLine("        {");
        sb.AppendLine("            length--;");
        sb.AppendLine("        }");
        sb.AppendLine("        return Asn1BitString.FromBits(bits.AsSpan(0, length));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer) => Encode(writer, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine("    public void Encode(Asn1Writer writer, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteBitString(tag, Value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader) => Decode(reader, DefaultTag);");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Decode(Asn1Reader reader, Asn1Tag tag)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {typeName} {{ Value = reader.ReadBitString(tag) }};");
        sb.AppendLine("    }");
        EmitDefaultTag(sb, type, constructed: false, fallback: "Asn1Tag.BitString");
        sb.AppendLine("}");
    }

    private void EmitProperty(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string typeName,
        IrComponent field,
        bool optional,
        bool privateSetter)
    {
        var prop = PropertyName(field, typeName);
        EmitCollapsedAliasDoc(sb, document, module, field.Type);
        var csType = CsType(document, module, typeName, field.Name, field.Type, optional);
        var effective = UnwrapAliases(document, module, field.Type);
        var setter = privateSetter ? "private set" : "set";
        var initializer = privateSetter ? "" : Initializer(effective, optional);
        sb.AppendLine($"    public {csType} {prop} {{ get; {setter}; }}{initializer}");
    }

    private void EmitCollapsedAliasDoc(StringBuilder sb, IrDocument document, IrModule module, TypeExpr type)
    {
        if (type is not RefType reference)
        {
            return;
        }

        var found = Find(document, module, reference);
        if (found is null || !IsCollapsibleAlias(found.Type))
        {
            return;
        }

        sb.AppendLine($"    /// <summary>ASN.1 alias {reference.Name} ::= {FormatAliasRhs(found.Type)}.</summary>");
    }

    private static string FormatAliasRhs(TypeExpr type) => type switch
    {
        BooleanType => "BOOLEAN",
        IntegerType => "INTEGER",
        EnumeratedType => "ENUMERATED",
        BitStringType => "BIT STRING",
        OctetStringType => "OCTET STRING",
        NullType => "NULL",
        OidType => "OBJECT IDENTIFIER",
        StringType stringType => stringType.Form switch
        {
            StringTypes.Utf8 => "UTF8String",
            StringTypes.Numeric => "NumericString",
            StringTypes.Printable => "PrintableString",
            StringTypes.Teletex => "TeletexString",
            StringTypes.T61 => "T61String",
            StringTypes.Videotex => "VideotexString",
            StringTypes.Ia5 => "IA5String",
            StringTypes.Graphic => "GraphicString",
            StringTypes.Visible => "VisibleString",
            StringTypes.General => "GeneralString",
            StringTypes.Universal => "UniversalString",
            StringTypes.Bmp => "BMPString",
            _ => "String"
        },
        TimeType timeType => timeType.Form == TimeTypes.Utc ? "UTCTime" : "GeneralizedTime",
        AnyType => "ANY",
        RefType reference => reference.Name,
        SequenceType => "SEQUENCE",
        SetType => "SET",
        ChoiceType => "CHOICE",
        SequenceOfType => "SEQUENCE OF",
        SetOfType => "SET OF",
        _ => type.Kind
    };

    private static void EmitDefaultTag(StringBuilder sb, TypeExpr type, bool constructed, string fallback)
    {
        var tag = type.Tag is null ? fallback : TagFromIr(type.Tag, constructed || type.Tag.Mode == TagModes.Explicit);
        sb.AppendLine();
        sb.AppendLine($"    public static Asn1Tag DefaultTag {{ get; }} = {tag};");
    }

    private void EmitEncodeField(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        IrComponent field,
        string indent,
        string writer)
    {
        var prop = PropertyName(field, owner);
        if (field.Optional)
        {
            sb.AppendLine($"{indent}if ({prop} != null)");
            sb.AppendLine($"{indent}{{");
            EmitEncodeValue(
                sb,
                document,
                module,
                owner,
                field.Name,
                field.Type,
                indent + "    ",
                writer,
                UnwrapOptional(document, module, field.Type, prop));
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            EmitEncodeValue(sb, document, module, owner, field.Name, field.Type, indent, writer, prop);
        }
    }

    private string UnwrapOptional(IrDocument document, IrModule module, TypeExpr type, string expr)
    {
        return IsValueOptionalWrapper(document, module, type) ? expr + ".Value" : expr;
    }

    private bool IsValueOptionalWrapper(IrDocument document, IrModule module, TypeExpr type)
    {
        var unwrapped = UnwrapAliases(document, module, type);
        return ResolvePrimitive(unwrapped) is TypeKinds.Boolean or TypeKinds.Integer or TypeKinds.Enumerated
            or TypeKinds.BitString or TypeKinds.Time or TypeKinds.Any;
    }

    private void EmitEncodeValue(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        string hint,
        TypeExpr type,
        string indent,
        string writer,
        string expr,
        string? forceTag = null)
    {
        type = UnwrapAliases(document, module, type);

        if (type.Tag?.Mode == TagModes.Explicit && forceTag is null)
        {
            sb.AppendLine($"{indent}{writer}.WriteExplicit({TagFromIr(type.Tag, constructed: true)}, nested =>");
            sb.AppendLine($"{indent}{{");
            var inner = CloneUntagged(type);
            EmitEncodeValue(sb, document, module, owner, hint, inner, indent + "    ", "nested", expr);
            sb.AppendLine($"{indent}}});");
            return;
        }

        if (type is AnyType)
        {
            if (forceTag is not null || type.Tag is not null)
            {
                var anyTag = forceTag ?? TagExpr(document, module, type);
                sb.AppendLine($"{indent}{writer}.WriteAny({anyTag}, {expr});");
            }
            else
            {
                sb.AppendLine($"{indent}{writer}.WriteAny({expr});");
            }

            return;
        }

        var tag = forceTag ?? TagExpr(document, module, type);
        var primitive = ResolvePrimitive(type);
        if (primitive is not null)
        {
            sb.AppendLine($"{indent}{WriteCall(writer, tag, expr, type)};");
            return;
        }

        if (type is RefType reference)
        {
            var resolved = Find(document, module, reference);
            if (resolved?.Type is ChoiceType or AnyType)
            {
                sb.AppendLine($"{indent}{expr}.Encode({writer});");
                return;
            }
        }

        if (type is ChoiceType)
        {
            sb.AppendLine($"{indent}{expr}.Encode({writer});");
            return;
        }

        sb.AppendLine($"{indent}{expr}.Encode({writer}, {tag});");
    }

    private void EmitDecodeField(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        IrComponent field,
        string indent,
        string reader,
        string target)
    {
        var prop = PropertyName(field, owner);
        if (field.Optional)
        {
            if (IsUntaggedAny(document, module, field.Type))
            {
                sb.AppendLine($"{indent}if (!{reader}.Eof)");
                sb.AppendLine($"{indent}{{");
                EmitDecodeAssign(sb, document, module, owner, field.Name, field.Type, indent + "    ", reader, $"{target}.{prop}");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                var peekTag = "tag_" + SanitizeIdentifier(field.Name);
                sb.AppendLine($"{indent}if ({reader}.TryPeekTag(out var {peekTag}) && {peekTag}.MatchesIgnoreConstructed({TagExpr(document, module, field.Type)}))");
                sb.AppendLine($"{indent}{{");
                EmitDecodeAssign(sb, document, module, owner, field.Name, field.Type, indent + "    ", reader, $"{target}.{prop}");
                sb.AppendLine($"{indent}}}");
            }
        }
        else
        {
            EmitDecodeAssign(sb, document, module, owner, field.Name, field.Type, indent, reader, $"{target}.{prop}");
        }
    }

    private bool IsUntaggedAny(IrDocument document, IrModule module, TypeExpr type)
    {
        if (type.Tag is not null)
        {
            return false;
        }

        var unwrapped = UnwrapAliases(document, module, type);
        return unwrapped is AnyType { Tag: null };
    }

    private void EmitDecodeAssign(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        string hint,
        TypeExpr type,
        string indent,
        string reader,
        string target,
        string? forceTag = null)
    {
        sb.Append(indent);
        sb.Append(target);
        sb.Append(" = ");
        EmitDecodeExpr(sb, document, module, owner, hint, type, reader, forceTag);
        sb.AppendLine(";");
    }

    private void EmitDecodeExpr(
        StringBuilder sb,
        IrDocument document,
        IrModule module,
        string owner,
        string hint,
        TypeExpr type,
        string reader,
        string? forceTag = null)
    {
        type = UnwrapAliases(document, module, type);

        if (type.Tag?.Mode == TagModes.Explicit && forceTag is null)
        {
            sb.Append($"{reader}.ReadSequence({TagFromIr(type.Tag, constructed: true)}, nested => ");
            EmitDecodeExpr(sb, document, module, owner, hint, CloneUntagged(type), "nested");
            sb.Append(')');
            return;
        }

        if (type is AnyType)
        {
            if (forceTag is not null || type.Tag is not null)
            {
                var anyTag = forceTag ?? TagExpr(document, module, type);
                sb.Append($"{reader}.ReadAny({anyTag})");
            }
            else
            {
                sb.Append($"{reader}.ReadAny()");
            }

            return;
        }

        var tag = forceTag ?? TagExpr(document, module, type);
        var primitive = ResolvePrimitive(type);
        if (primitive is not null)
        {
            sb.Append(ReadCall(reader, tag, type));
            return;
        }

        var typeName = NamedTypeName(document, module, owner, hint, type);
        if (type is ChoiceType ||
            (type is RefType r && Find(document, module, r)?.Type is ChoiceType or AnyType))
        {
            sb.Append($"{typeName}.Decode({reader})");
            return;
        }

        sb.Append($"{typeName}.Decode({reader}, {tag})");
    }

    private string CsType(IrDocument document, IrModule module, string owner, string hint, TypeExpr type, bool optional)
    {
        type = UnwrapAliases(document, module, type);
        var primitive = ResolvePrimitive(type);
        if (primitive is not null)
        {
            var mapped = primitive switch
            {
                TypeKinds.Boolean => optional ? "bool?" : "bool",
                TypeKinds.Integer or TypeKinds.Enumerated => optional ? "BigInteger?" : "BigInteger",
                TypeKinds.OctetString => optional ? "byte[]?" : "byte[]",
                TypeKinds.Null => optional ? "bool?" : "bool",
                TypeKinds.Oid => optional ? "string?" : "string",
                TypeKinds.BitString => optional ? "Asn1BitString?" : "Asn1BitString",
                TypeKinds.String => optional ? "string?" : "string",
                TypeKinds.Time => optional ? "DateTimeOffset?" : "DateTimeOffset",
                TypeKinds.Any => optional ? "Asn1Any?" : "Asn1Any",
                _ => "object"
            };
            return mapped;
        }

        var name = NamedTypeName(document, module, owner, hint, type);
        return optional ? name + "?" : name;
    }

    private string NamedTypeName(IrDocument document, IrModule module, string owner, string hint, TypeExpr type)
    {
        if (type is RefType reference)
        {
            var found = FindWithModule(document, module, reference);
            if (found is not null)
            {
                var (definingModule, def) = found.Value;
                var typeName = IrOptions.CSharpTypeName(def.Options) ?? SanitizeIdentifier(def.Name);
                var currentNs = ModuleNamespace(module);
                var definingNs = ModuleNamespace(definingModule);
                if (!string.Equals(currentNs, definingNs, StringComparison.Ordinal))
                {
                    return definingNs + "." + typeName;
                }

                return typeName;
            }

            return SanitizeIdentifier(reference.Name);
        }

        if (NeedsNamedType(type))
        {
            return owner + "_" + SanitizeIdentifier(hint);
        }

        return SanitizeIdentifier(hint);
    }

    private static string ModuleNamespace(IrModule module) =>
        IrOptions.CSharpNamespace(module.Options) ?? SanitizeIdentifier(module.Name);

    private static string Initializer(TypeExpr type, bool optional)
    {
        if (optional)
        {
            return "";
        }

        return type switch
        {
            OctetStringType => " = Array.Empty<byte>();",
            OidType => " = \"\";",
            StringType => " = \"\";",
            SequenceOfType or SetOfType => " = new();",
            _ => ""
        };
    }

    private string TagExpr(IrDocument document, IrModule module, TypeExpr type)
    {
        type = UnwrapAliases(document, module, type);
        if (type.Tag is not null)
        {
            var constructed = type.Tag.Mode == TagModes.Explicit || IsConstructed(document, module, type);
            return TagFromIr(type.Tag, constructed);
        }

        return UniversalTag(document, module, type);
    }

    private static string TagFromIr(IrTag tag, bool constructed)
    {
        var cls = tag.Class.ToLowerInvariant() switch
        {
            TagClasses.Universal => "Asn1TagClass.Universal",
            TagClasses.Application => "Asn1TagClass.Application",
            TagClasses.Private => "Asn1TagClass.Private",
            _ => "Asn1TagClass.ContextSpecific"
        };

        return $"new Asn1Tag({cls}, {tag.Number.ToString(CultureInfo.InvariantCulture)}, {(constructed ? "true" : "false")})";
    }

    private string UniversalTag(IrDocument document, IrModule module, TypeExpr type)
    {
        return type switch
        {
            BooleanType => "Asn1Tag.Boolean",
            IntegerType or EnumeratedType => "Asn1Tag.Integer",
            BitStringType => "Asn1Tag.BitString",
            OctetStringType => "Asn1Tag.OctetString",
            NullType => "Asn1Tag.Null",
            OidType => "Asn1Tag.ObjectIdentifier",
            StringType stringType => StringFormTag(stringType.Form),
            TimeType timeType => TimeFormTag(timeType.Form),
            SetType or SetOfType => "Asn1Tag.Set",
            SequenceType or SequenceOfType => "Asn1Tag.Sequence",
            RefType reference when Find(document, module, reference)?.Type is { } inner =>
                UniversalTag(document, module, inner),
            _ => "Asn1Tag.Sequence"
        };
    }

    private string UniversalFallback(IrDocument document, IrModule module, TypeExpr type) =>
        UniversalTag(document, module, type);

    private static string StringFormTag(string form) => form switch
    {
        StringTypes.Utf8 => "Asn1Tag.Utf8String",
        StringTypes.Numeric => "Asn1Tag.NumericString",
        StringTypes.Printable => "Asn1Tag.PrintableString",
        StringTypes.Teletex or StringTypes.T61 => "Asn1Tag.TeletexString",
        StringTypes.Videotex => "Asn1Tag.VideotexString",
        StringTypes.Ia5 => "Asn1Tag.Ia5String",
        StringTypes.Graphic => "Asn1Tag.GraphicString",
        StringTypes.Visible => "Asn1Tag.VisibleString",
        StringTypes.General => "Asn1Tag.GeneralString",
        StringTypes.Universal => "Asn1Tag.UniversalString",
        StringTypes.Bmp => "Asn1Tag.BmpString",
        _ => throw new NotSupportedException($"Unknown stringType '{form}'.")
    };

    private static string TimeFormTag(string form) => form switch
    {
        TimeTypes.Utc => "Asn1Tag.UtcTime",
        TimeTypes.Generalized => "Asn1Tag.GeneralizedTime",
        _ => throw new NotSupportedException($"Unknown timeType '{form}'.")
    };

    private static string StringFormEnum(string form) => form switch
    {
        StringTypes.Utf8 => "Asn1StringForm.Utf8",
        StringTypes.Printable => "Asn1StringForm.Printable",
        StringTypes.Teletex => "Asn1StringForm.Teletex",
        StringTypes.T61 => "Asn1StringForm.T61",
        StringTypes.Ia5 => "Asn1StringForm.Ia5",
        StringTypes.Numeric => "Asn1StringForm.Numeric",
        StringTypes.Visible => "Asn1StringForm.Visible",
        StringTypes.Bmp => "Asn1StringForm.Bmp",
        StringTypes.Universal => "Asn1StringForm.Universal",
        StringTypes.General => "Asn1StringForm.General",
        StringTypes.Graphic => "Asn1StringForm.Graphic",
        StringTypes.Videotex => "Asn1StringForm.Videotex",
        _ => throw new NotSupportedException($"Unknown stringType '{form}'.")
    };

    private static string TimeFormEnum(string form) => form switch
    {
        TimeTypes.Utc => "Asn1TimeForm.Utc",
        TimeTypes.Generalized => "Asn1TimeForm.Generalized",
        _ => throw new NotSupportedException($"Unknown timeType '{form}'.")
    };

    private string? ResolvePrimitive(TypeExpr type) => type switch
    {
        BooleanType => TypeKinds.Boolean,
        IntegerType => TypeKinds.Integer,
        EnumeratedType => TypeKinds.Enumerated,
        BitStringType => TypeKinds.BitString,
        OctetStringType => TypeKinds.OctetString,
        NullType => TypeKinds.Null,
        OidType => TypeKinds.Oid,
        StringType => TypeKinds.String,
        TimeType => TypeKinds.Time,
        AnyType => TypeKinds.Any,
        _ => null
    };

    /// <summary>
    /// Collapse typedef aliases to the underlying type used in generated C#.
    /// Stops at constructed named types and named BIT STRING (those keep a class).
    /// </summary>
    private TypeExpr UnwrapAliases(IrDocument document, IrModule module, TypeExpr type)
    {
        var visited = new HashSet<string>(StringComparer.Ordinal);
        while (type is RefType reference)
        {
            var key = (reference.Module ?? module.Name) + "::" + reference.Name;
            if (!visited.Add(key))
            {
                throw new NotSupportedException($"Circular type alias '{reference.Name}'.");
            }

            var found = FindWithModule(document, module, reference);
            if (found is null)
            {
                return type;
            }

            var inner = found.Value.Def.Type;
            if (IsNamedBitString(inner) || NeedsNamedType(inner))
            {
                return type;
            }

            var next = CloneType(inner);
            if (type.Tag is not null && next.Tag is null)
            {
                next.Tag = type.Tag;
            }

            type = next;
        }

        return type;
    }

    private static TypeExpr CloneType(TypeExpr type)
    {
        var clone = CloneUntagged(type);
        clone.Tag = type.Tag;
        return clone;
    }

    private bool IsConstructed(IrDocument document, IrModule module, TypeExpr type) => type switch
    {
        SequenceType or SetType or SequenceOfType or SetOfType or ChoiceType => true,
        RefType reference => Find(document, module, reference)?.Type is { } inner && IsConstructed(document, module, inner),
        _ => false
    };

    private IEnumerable<IrComponent> SortedSetComponents(
        IrDocument document,
        IrModule module,
        IReadOnlyList<IrComponent> components) =>
        components
            .Select((component, index) => (component, index, key: ComponentTagSortKey(document, module, component.Type)))
            .OrderBy(x => x.key.TagClass)
            .ThenBy(x => x.key.Number)
            .ThenBy(x => x.index)
            .Select(x => x.component);

    private (int TagClass, int Number) ComponentTagSortKey(IrDocument document, IrModule module, TypeExpr type)
    {
        type = UnwrapAliases(document, module, type);
        if (type.Tag is not null)
        {
            return (TagClassOrdinal(type.Tag.Class), type.Tag.Number);
        }

        return (0, UniversalTagNumber(document, module, type));
    }

    private static int TagClassOrdinal(string tagClass) => tagClass.ToLowerInvariant() switch
    {
        TagClasses.Universal => 0,
        TagClasses.Application => 1,
        TagClasses.Private => 3,
        _ => 2
    };

    private int UniversalTagNumber(IrDocument document, IrModule module, TypeExpr type) => type switch
    {
        BooleanType => 1,
        IntegerType or EnumeratedType => 2,
        BitStringType => 3,
        OctetStringType => 4,
        NullType => 5,
        OidType => 6,
        StringType stringType => StringFormTagNumber(stringType.Form),
        TimeType timeType => timeType.Form == TimeTypes.Utc ? 23 : 24,
        SequenceType or SequenceOfType => 16,
        SetType or SetOfType => 17,
        RefType reference when Find(document, module, reference)?.Type is { } inner =>
            UniversalTagNumber(document, module, inner),
        _ => 16
    };

    private static int StringFormTagNumber(string form) => form switch
    {
        StringTypes.Utf8 => 12,
        StringTypes.Numeric => 18,
        StringTypes.Printable => 19,
        StringTypes.Teletex or StringTypes.T61 => 20,
        StringTypes.Videotex => 21,
        StringTypes.Ia5 => 22,
        StringTypes.Graphic => 25,
        StringTypes.Visible => 26,
        StringTypes.General => 27,
        StringTypes.Universal => 28,
        StringTypes.Bmp => 30,
        _ => throw new NotSupportedException($"Unknown stringType '{form}'.")
    };

    private static IrTypeDef? Find(IrDocument document, IrModule module, RefType reference) =>
        FindWithModule(document, module, reference)?.Def;

    private static (IrModule Module, IrTypeDef Def)? FindWithModule(
        IrDocument document,
        IrModule module,
        RefType reference)
    {
        var modules = string.IsNullOrEmpty(reference.Module)
            ? new[] { module }.Concat(document.Modules)
            : document.Modules.Where(m => m.Name == reference.Module);
        foreach (var candidate in modules)
        {
            var match = candidate.Types.FirstOrDefault(t => t.Name == reference.Name);
            if (match is not null)
            {
                return (candidate, match);
            }
        }

        return null;
    }

    private static TypeExpr CloneUntagged(TypeExpr type)
    {
        var clone = type switch
        {
            BooleanType => (TypeExpr)new BooleanType(),
            NullType => new NullType(),
            OctetStringType => new OctetStringType(),
            OidType => new OidType(),
            IntegerType integer => new IntegerType { NamedValues = integer.NamedValues },
            EnumeratedType enumerated => new EnumeratedType { Values = enumerated.Values },
            BitStringType bitString => new BitStringType { NamedBits = bitString.NamedBits },
            StringType stringType => new StringType { Form = stringType.Form },
            TimeType timeType => new TimeType { Form = timeType.Form, FractionDigits = timeType.FractionDigits },
            AnyType any => new AnyType { DefinedBy = any.DefinedBy },
            SequenceType sequence => new SequenceType { Components = sequence.Components },
            SetType set => new SetType { Components = set.Components, Extensible = set.Extensible },
            ChoiceType choice => new ChoiceType { Components = choice.Components },
            SequenceOfType sequenceOf => new SequenceOfType { Element = sequenceOf.Element },
            SetOfType setOf => new SetOfType { Element = setOf.Element },
            RefType reference => new RefType { Name = reference.Name, Module = reference.Module },
            _ => throw new NotSupportedException($"Cannot clone untagged type kind '{type.Kind}'.")
        };
        clone.Options = type.Options;
        clone.Constraint = type.Constraint;
        return clone;
    }

    private static string WriteCall(string writer, string tag, string expr, TypeExpr type) => type switch
    {
        BooleanType => $"{writer}.WriteBoolean({tag}, {expr})",
        IntegerType or EnumeratedType => $"{writer}.WriteInteger({tag}, {expr})",
        BitStringType => $"{writer}.WriteBitString({tag}, {expr})",
        OctetStringType => $"{writer}.WriteOctetString({tag}, {expr})",
        NullType => $"{writer}.WriteNull({tag})",
        OidType => $"{writer}.WriteObjectIdentifier({tag}, {expr})",
        StringType stringType => $"{writer}.WriteString({tag}, {expr}, {StringFormEnum(stringType.Form)})",
        TimeType timeType => timeType.Form == TimeTypes.Generalized
            ? $"{writer}.WriteTime({tag}, {expr}, {TimeFormEnum(timeType.Form)}, {timeType.FractionDigits ?? 3})"
            : $"{writer}.WriteTime({tag}, {expr}, {TimeFormEnum(timeType.Form)})",
        _ => throw new InvalidOperationException(type.Kind)
    };

    private static string ReadCall(string reader, string tag, TypeExpr type) => type switch
    {
        BooleanType => $"{reader}.ReadBoolean({tag})",
        IntegerType or EnumeratedType => $"{reader}.ReadInteger({tag})",
        BitStringType => $"{reader}.ReadBitString({tag})",
        OctetStringType => $"{reader}.ReadOctetString({tag})",
        NullType => $"{reader}.ReadNull({tag})",
        OidType => $"{reader}.ReadObjectIdentifier({tag})",
        StringType stringType => $"{reader}.ReadString({tag}, {StringFormEnum(stringType.Form)})",
        TimeType timeType => $"{reader}.ReadTime({tag}, {TimeFormEnum(timeType.Form)})",
        _ => throw new InvalidOperationException(type.Kind)
    };

    private static string PropertyName(IrComponent field, string? enclosingTypeName = null)
    {
        var name = IrOptions.CSharpPropertyName(field.Options) ?? SanitizeIdentifier(field.Name);
        if (Keywords.Contains(name))
        {
            name = "@" + name;
        }

        if (enclosingTypeName is not null &&
            string.Equals(name, enclosingTypeName, StringComparison.Ordinal))
        {
            name += "Value";
        }

        return name;
    }

    internal static string SanitizeIdentifier(string name)
    {
        var parts = name.Split(new[] { '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
        var result = string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : "")));
        return string.IsNullOrEmpty(result) ? "Type" : result;
    }
}
